[build]
  base = "frontend"
  publish = "build"
  command = "npm ci --include=dev && npm run build"

# Deploy from master branch
[context.production]
  branch = "master"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"

# Serverless functions configuration
[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

# Redirects for API and SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (will be set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "development"
