[build]
  base = "frontend"
  publish = "build"
  command = "npm ci --include=dev && cd ../backend && npm ci && npm run build && cd ../frontend && npm ci --include=dev && npm run build && cd ../netlify/functions && npm install"

# Deploy from master branch
[context.production]
  branch = "master"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"

# Serverless functions configuration
[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

# Redirects for API and SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (will be set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  # IMPORTANT: Set these sensitive values in Netlify dashboard, NOT in this file:
  # - MONGODB_URI (your MongoDB Atlas connection string)
  # - JWT_SECRET (32+ character secret key)
  # - JWT_REFRESH_SECRET (different 32+ character secret key)
  # - FRONTEND_URL (your actual Netlify domain)
  # - CORS_ORIGIN (your actual Netlify domain)
  
[context.deploy-preview.environment]
  NODE_ENV = "development"
