[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirects for SPA routing only
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
